export const CURRENCY_COUNTRIES = {
  AED: { en: 'United Arab Emirates', ar: 'الإمارات' },
  AFN: { en: 'Afghanistan', ar: 'أفغانستان' },
  ALL: { en: 'Albania', ar: 'ألبانيا' },
  AMD: { en: 'Armenia', ar: 'أرمينيا' },
  ANG: { en: 'Curaçao and Sint Maarten', ar: 'كوراساو وسانت مارتن' },
  AOA: { en: 'Angola', ar: 'أنغولا' },
  ARS: { en: 'Argentina', ar: 'الأرجنتين' },
  AUD: { en: 'Australia', ar: 'أستراليا' },
  AWG: { en: 'Aruba', ar: 'أروبا' },
  AZN: { en: 'Azerbaijan', ar: 'أذربيجان' },
  BAM: { en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  BBD: { en: 'Barbados', ar: 'بربادوس' },
  BDT: { en: 'Bangladesh', ar: 'بنغلاديش' },
  BGN: { en: 'Bulgaria', ar: 'بلغاريا' },
  BHD: { en: 'Bahrain', ar: 'البحرين' },
  BIF: { en: 'Burundi', ar: 'بوروندي' },
  BMD: { en: 'Bermuda', ar: 'برمودا' },
  BND: { en: 'Brunei', ar: 'بروناي' },
  BOB: { en: 'Bolivia', ar: 'بوليفيا' },
  BRL: { en: 'Brazil', ar: 'البرازيل' },
  BSD: { en: 'Bahamas', ar: 'باهاماس' },
  BTN: { en: 'Bhutan', ar: 'بوتان' },
  BWP: { en: 'Botswana', ar: 'بوتسوانا' },
  BYN: { en: 'Belarus', ar: 'بيلاروسيا' },
  BZD: { en: 'Belize', ar: 'بليز' },
  CAD: { en: 'Canada', ar: 'كندا' },
  CDF: { en: 'Democratic Republic of the Congo', ar: 'جمهورية الكونغو الديمقراطية' },
  CHF: { en: 'Switzerland', ar: 'سويسرا' },
  CLP: { en: 'Chile', ar: 'تشيلي' },
  CNY: { en: 'China', ar: 'الصين' },
  COP: { en: 'Colombia', ar: 'كولومبيا' },
  CRC: { en: 'Costa Rica', ar: 'كوستاريكا' },
  CUP: { en: 'Cuba', ar: 'كوبا' },
  CVE: { en: 'Cape Verde', ar: 'الرأس الأخضر' },
  CZK: { en: 'Czechia', ar: 'التشيك' },
  DJF: { en: 'Djibouti', ar: 'جيبوتي' },
  DKK: { en: 'Denmark', ar: 'الدنمارك' },
  DOP: { en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
  DZD: { en: 'Algeria', ar: 'الجزائر' },
  EGP: { en: 'Egypt', ar: 'مصر' },
  ERN: { en: 'Eritrea', ar: 'إريتريا' },
  ETB: { en: 'Ethiopia', ar: 'إثيوبيا' },
  EUR: { en: 'Eurozone', ar: 'منطقة اليورو' },
  FJD: { en: 'Fiji', ar: 'فيجي' },
  FKP: { en: 'Falkland Islands', ar: 'جزر فوكلاند' },
  GBP: { en: 'United Kingdom', ar: 'المملكة المتحدة' },
  GEL: { en: 'Georgia', ar: 'جورجيا' },
  GHS: { en: 'Ghana', ar: 'غانا' },
  GIP: { en: 'Gibraltar', ar: 'جبل طارق' },
  GMD: { en: 'The Gambia', ar: 'غامبيا' },
  GNF: { en: 'Guinea', ar: 'غينيا' },
  GTQ: { en: 'Guatemala', ar: 'غواتيمالا' },
  GYD: { en: 'Guyana', ar: 'غيانا' },
  HKD: { en: 'Hong Kong', ar: 'هونغ كونغ' },
  HNL: { en: 'Honduras', ar: 'هندوراس' },
  HRK: { en: 'Croatia', ar: 'كرواتيا' },
  HTG: { en: 'Haiti', ar: 'هايتي' },
  HUF: { en: 'Hungary', ar: 'المجر' },
  IDR: { en: 'Indonesia', ar: 'إندونيسيا' },
  ILS: { en: 'Israel and Palestine', ar: 'فلسطين وإسرائيل' },
  INR: { en: 'India', ar: 'الهند' },
  IQD: { en: 'Iraq', ar: 'العراق' },
  IRR: { en: 'Iran', ar: 'إيران' },
  ISK: { en: 'Iceland', ar: 'آيسلندا' },
  JMD: { en: 'Jamaica', ar: 'جامايكا' },
  JOD: { en: 'Jordan', ar: 'الأردن' },
  JPY: { en: 'Japan', ar: 'اليابان' },
  KES: { en: 'Kenya', ar: 'كينيا' },
  KGS: { en: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  KHR: { en: 'Cambodia', ar: 'كمبوديا' },
  KMF: { en: 'Comoros', ar: 'جزر القمر' },
  KRW: { en: 'South Korea', ar: 'كوريا الجنوبية' },
  KWD: { en: 'Kuwait', ar: 'الكويت' },
  KYD: { en: 'Cayman Islands', ar: 'جزر كايمان' },
  KZT: { en: 'Kazakhstan', ar: 'كازاخستان' },
  LAK: { en: 'Laos', ar: 'لاوس' },
  LBP: { en: 'Lebanon', ar: 'لبنان' },
  LKR: { en: 'Sri Lanka', ar: 'سريلانكا' },
  LRD: { en: 'Liberia', ar: 'ليبيريا' },
  LSL: { en: 'Lesotho', ar: 'ليسوتو' },
  LYD: { en: 'Libya', ar: 'ليبيا' },
  MAD: { en: 'Morocco', ar: 'المغرب' },
  MDL: { en: 'Moldova', ar: 'مولدوفا' },
  MGA: { en: 'Madagascar', ar: 'مدغشقر' },
  MKD: { en: 'North Macedonia', ar: 'مقدونيا الشمالية' },
  MMK: { en: 'Myanmar', ar: 'ميانمار' },
  MNT: { en: 'Mongolia', ar: 'منغوليا' },
  MOP: { en: 'Macau', ar: 'ماكاو' },
  MRU: { en: 'Mauritania', ar: 'موريتانيا' },
  MUR: { en: 'Mauritius', ar: 'موريشيوس' },
  MVR: { en: 'Maldives', ar: 'المالديف' },
  MWK: { en: 'Malawi', ar: 'مالاوي' },
  MXN: { en: 'Mexico', ar: 'المكسيك' },
  MYR: { en: 'Malaysia', ar: 'ماليزيا' },
  MZN: { en: 'Mozambique', ar: 'موزمبيق' },
  NAD: { en: 'Namibia', ar: 'ناميبيا' },
  NGN: { en: 'Nigeria', ar: 'نيجيريا' },
  NIO: { en: 'Nicaragua', ar: 'نيكاراغوا' },
  NOK: { en: 'Norway', ar: 'النرويج' },
  NPR: { en: 'Nepal', ar: 'نيبال' },
  NZD: { en: 'New Zealand', ar: 'نيوزيلندا' },
  OMR: { en: 'Oman', ar: 'عمان' },
  PAB: { en: 'Panama', ar: 'بنما' },
  PEN: { en: 'Peru', ar: 'بيرو' },
  PGK: { en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
  PHP: { en: 'Philippines', ar: 'الفلبين' },
  PKR: { en: 'Pakistan', ar: 'باكستان' },
  PLN: { en: 'Poland', ar: 'بولندا' },
  PYG: { en: 'Paraguay', ar: 'باراغواي' },
  QAR: { en: 'Qatar', ar: 'قطر' },
  RON: { en: 'Romania', ar: 'رومانيا' },
  RSD: { en: 'Serbia', ar: 'صربيا' },
  RUB: { en: 'Russia', ar: 'روسيا' },
  RWF: { en: 'Rwanda', ar: 'رواندا' },
  SAR: { en: 'Saudi Arabia', ar: 'السعودية' },
  SBD: { en: 'Solomon Islands', ar: 'جزر سليمان' },
  SCR: { en: 'Seychelles', ar: 'سيشل' },
  SDG: { en: 'Sudan', ar: 'السودان' },
  SEK: { en: 'Sweden', ar: 'السويد' },
  SGD: { en: 'Singapore', ar: 'سنغافورة' },
  SHP: { en: 'Saint Helena', ar: 'سانت هيلينا' },
  SLE: { en: 'Sierra Leone', ar: 'سيراليون' },
  SOS: { en: 'Somalia', ar: 'الصومال' },
  SRD: { en: 'Suriname', ar: 'سورينام' },
  STN: { en: 'São Tomé and Príncipe', ar: 'ساو تومي وبرينسيبي' },
  SYP: { en: 'Syria', ar: 'سوريا' },
  SZL: { en: 'Eswatini', ar: 'إسواتيني' },
  THB: { en: 'Thailand', ar: 'تايلاند' },
  TJS: { en: 'Tajikistan', ar: 'طاجيكستان' },
  TMT: { en: 'Turkmenistan', ar: 'تركمانستان' },
  TND: { en: 'Tunisia', ar: 'تونس' },
  TOP: { en: 'Tonga', ar: 'تونغا' },
  TRY: { en: 'Turkey', ar: 'تركيا' },
  TTD: { en: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو' },
  TWD: { en: 'Taiwan', ar: 'تايوان' },
  TZS: { en: 'Tanzania', ar: 'تنزانيا' },
  UAH: { en: 'Ukraine', ar: 'أوكرانيا' },
  UGX: { en: 'Uganda', ar: 'أوغندا' },
  USD: { en: 'United States', ar: 'الولايات المتحدة' },
  UYU: { en: 'Uruguay', ar: 'أوروغواي' },
  UZS: { en: 'Uzbekistan', ar: 'أوزبكستان' },
  VES: { en: 'Venezuela', ar: 'فنزويلا' },
  VND: { en: 'Vietnam', ar: 'فيتنام' },
  VUV: { en: 'Vanuatu', ar: 'فانواتو' },
  WST: { en: 'Samoa', ar: 'ساموا' },
  XAF: { en: 'Central Africa', ar: 'وسط أفريقيا' },
  XCD: { en: 'Eastern Caribbean', ar: 'شرق الكاريبي' },
  XOF: { en: 'West Africa', ar: 'غرب أفريقيا' },
  XPF: { en: 'French Pacific territories', ar: 'مناطق المحيط الهادئ الفرنسية' },
  YER: { en: 'Yemen', ar: 'اليمن' },
  ZAR: { en: 'South Africa', ar: 'جنوب أفريقيا' },
  ZMW: { en: 'Zambia', ar: 'زامبيا' },
  ZWL: { en: 'Zimbabwe', ar: 'زيمبابوي' },
};

export const FALLBACK_RATES = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.78,
  EGP: 48.5,
  SAR: 3.75,
  AED: 3.67,
  KWD: 0.31,
  QAR: 3.64,
  JOD: 0.71,
  BHD: 0.38,
  OMR: 0.38,
  JPY: 156,
  CNY: 7.2,
  INR: 83.5,
  CAD: 1.36,
  AUD: 1.5,
  TRY: 32.8,
};

export function getCurrencyCountry(code, locale = 'en') {
  return CURRENCY_COUNTRIES[code]?.[locale] || (locale === 'ar' ? 'دول متعددة' : 'Multiple countries');
}

export function getCurrencyLabel(code, locale = 'en') {
  let currencyName = code;

  try {
    currencyName = new Intl.DisplayNames([locale === 'ar' ? 'ar' : 'en'], { type: 'currency' }).of(code) || code;
  } catch (error) {
    currencyName = code;
  }

  return `${code} - ${currencyName} - ${getCurrencyCountry(code, locale)}`;
}
